settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: app
  path: .
  commands:
    run:
      status: true
    test:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - vendor
